export const indianCities = [
  "Mumbai, Maharashtra",
  "Delhi, Delhi",
  "Bengaluru, Karnataka",
  "Hyderabad, Telangana",
  "Ahmedabad, Gujarat",
  "Chennai, Tamil Nadu",
  "Kolkata, West Bengal",
  "Surat, Gujarat",
  "Pune, Maharashtra",
  "Jaipur, Rajasthan",
  "Lucknow, Uttar Pradesh",
  "Kanpur, Uttar Pradesh",
  "Nagpur, Maharashtra",
  "Indore, Madhya Pradesh",
  "Thane, Maharashtra",
  "Bhopal, Madhya Pradesh",
  "Visakhapatnam, Andhra Pradesh",
  "Pimpri-Chinchwad, Maharashtra",
  "Patna, Bihar",
  "Vadodara, Gujarat",
  "Ghaziabad, Uttar Pradesh",
  "Ludhiana, Punjab",
  "Agra, Uttar Pradesh",
  "Nashik, Maharashtra",
  "Faridabad, Haryana",
  "Meerut, Uttar Pradesh",
  "Rajkot, Gujarat",
  "Kalyan-Dombivli, Maharashtra",
  "Vasai-Virar, Maharashtra",
  "Varanasi, Uttar Pradesh",
  "Srinagar, Jammu and Kashmir",
  "Aurangabad, Maharashtra",
  "Dhanbad, Jharkhand",
  "Amritsar, Punjab",
  "Navi Mumbai, Maharashtra",
  "Allahabad, Uttar Pradesh",
  "Howrah, West Bengal",
  "Ranchi, Jharkhand",
  "Gwalior, Madhya Pradesh",
  "Jabalpur, Madhya Pradesh",
  "Coimbatore, Tamil Nadu",
  "Vijayawada, Andhra Pradesh",
  "Jodhpur, Rajasthan",
  "Madurai, Tamil Nadu",
  "Raipur, Chhattisgarh",
  "Kota, Rajasthan",
  "Chandigarh, Chandigarh",
  "Guwahati, Assam",
  "Solapur, Maharashtra",
  "Hubli-Dharwad, Karnataka",
  "Mysore, Karnataka",
  "Tiruchirappalli, Tamil Nadu",
  "Bareilly, Uttar Pradesh",
  "Aligarh, Uttar Pradesh",
  "Tiruppur, Tamil Nadu",
  "Gurgaon, Haryana",
  "Moradabad, Uttar Pradesh",
  "Jalandhar, Punjab",
  "Bhubaneswar, Odisha",
  "Salem, Tamil Nadu",
  "Warangal, Telangana",
  "Mira-Bhayandar, Maharashtra",
  "Jalgaon, Maharashtra",
  "Guntur, Andhra Pradesh",
  "Thiruvananthapuram, Kerala",
  "Bhiwandi, Maharashtra",
  "Saharanpur, Uttar Pradesh",
  "Gorakhpur, Uttar Pradesh",
  "Bikaner, Rajasthan",
  "Amravati, Maharashtra",
  "Noida, Uttar Pradesh",
  "Jamshedpur, Jharkhand",
  "Bhilai, Chhattisgarh",
  "Cuttack, Odisha",
  "Firozabad, Uttar Pradesh",
  "Kochi, Kerala",
  "Bhavnagar, Gujarat",
  "Dehradun, Uttarakhand",
  "Durgapur, West Bengal",
  "Asansol, West Bengal",
  "Nanded, Maharashtra",
  "Kolhapur, Maharashtra",
  "Ajmer, Rajasthan",
  "Gulbarga, Karnataka",
  "Jamnagar, Gujarat",
  "Ujjain, Madhya Pradesh",
  "Loni, Uttar Pradesh",
  "Siliguri, West Bengal",
  "Jhansi, Uttar Pradesh",
  "Ulhasnagar, Maharashtra",
  "Jammu, Jammu and Kashmir",
  "Sangli-Miraj & Kupwad, Maharashtra",
  "Mangalore, Karnataka",
  "Erode, Tamil Nadu",
  "Belgaum, Karnataka",
  "Ambattur, Tamil Nadu",
  "Tirunelveli, Tamil Nadu",
  "Malegaon, Maharashtra",
  "Gaya, Bihar",
  "Udaipur, Rajasthan",
  "Dahod, Gujarat"
];
