-- Make fields optional in clients
ALTER TABLE clients ALTER COLUMN company DROP NOT NULL;
ALTER TABLE clients ALTER COLUMN email DROP NOT NULL;
ALTER TABLE clients ALTER COLUMN phone DROP NOT NULL;
ALTER TABLE clients ALTER COLUMN "avatarSeed" DROP NOT NULL;
ALTER TABLE clients ALTER COLUMN "avatarSeed" SET DEFAULT 'default_avatar';
ALTER TABLE clients ALTER COLUMN status DROP NOT NULL;
ALTER TABLE clients ALTER COLUMN status SET DEFAULT 'active';
ALTER TABLE clients ALTER COLUMN "totalValue" DROP NOT NULL;
ALTER TABLE clients ALTER COLUMN "totalValue" SET DEFAULT 0;
ALTER TABLE clients ALTER COLUMN "projectsCount" DROP NOT NULL;
ALTER TABLE clients ALTER COLUMN "projectsCount" SET DEFAULT 0;
ALTER TABLE clients ALTER COLUMN "joinedDate" DROP NOT NULL;
ALTER TABLE clients ALTER COLUMN "joinedDate" SET DEFAULT CURRENT_DATE;
ALTER TABLE clients ALTER COLUMN location DROP NOT NULL;
ALTER TABLE clients ALTER COLUMN tags DROP NOT NULL;
ALTER TABLE clients ALTER COLUMN tags SET DEFAULT '{}';

-- Make fields optional in leads
ALTER TABLE leads ALTER COLUMN company DROP NOT NULL;
ALTER TABLE leads ALTER COLUMN email DROP NOT NULL;
ALTER TABLE leads ALTER COLUMN source DROP NOT NULL;
ALTER TABLE leads ALTER COLUMN source SET DEFAULT 'Unknown';
ALTER TABLE leads ALTER COLUMN value DROP NOT NULL;
ALTER TABLE leads ALTER COLUMN value SET DEFAULT 0;
ALTER TABLE leads ALTER COLUMN stage DROP NOT NULL;
ALTER TABLE leads ALTER COLUMN stage SET DEFAULT 'new';
ALTER TABLE leads ALTER COLUMN probability DROP NOT NULL;
ALTER TABLE leads ALTER COLUMN probability SET DEFAULT 0;
ALTER TABLE leads ALTER COLUMN "assignedTo" DROP NOT NULL;
ALTER TABLE leads ALTER COLUMN "assignedTo" SET DEFAULT 'Unassigned';
ALTER TABLE leads ALTER COLUMN "createdDate" DROP NOT NULL;
ALTER TABLE leads ALTER COLUMN "createdDate" SET DEFAULT CURRENT_DATE;
ALTER TABLE leads ALTER COLUMN "lastContact" DROP NOT NULL;
ALTER TABLE leads ALTER COLUMN "lastContact" SET DEFAULT CURRENT_DATE;

-- Make fields optional in projects
ALTER TABLE projects ALTER COLUMN client DROP NOT NULL;
ALTER TABLE projects ALTER COLUMN status DROP NOT NULL;
ALTER TABLE projects ALTER COLUMN status SET DEFAULT 'planning';
ALTER TABLE projects ALTER COLUMN progress DROP NOT NULL;
ALTER TABLE projects ALTER COLUMN progress SET DEFAULT 0;
ALTER TABLE projects ALTER COLUMN budget DROP NOT NULL;
ALTER TABLE projects ALTER COLUMN budget SET DEFAULT 0;
ALTER TABLE projects ALTER COLUMN spent DROP NOT NULL;
ALTER TABLE projects ALTER COLUMN spent SET DEFAULT 0;
ALTER TABLE projects ALTER COLUMN "startDate" DROP NOT NULL;
ALTER TABLE projects ALTER COLUMN "startDate" SET DEFAULT CURRENT_DATE;
ALTER TABLE projects ALTER COLUMN "dueDate" DROP NOT NULL;
ALTER TABLE projects ALTER COLUMN "dueDate" SET DEFAULT CURRENT_DATE;
ALTER TABLE projects ALTER COLUMN team DROP NOT NULL;
ALTER TABLE projects ALTER COLUMN team SET DEFAULT '{}';
ALTER TABLE projects ALTER COLUMN priority DROP NOT NULL;
ALTER TABLE projects ALTER COLUMN priority SET DEFAULT 'medium';

-- Make fields optional in tasks
ALTER TABLE tasks ALTER COLUMN project DROP NOT NULL;
ALTER TABLE tasks ALTER COLUMN assignee DROP NOT NULL;
ALTER TABLE tasks ALTER COLUMN assignee SET DEFAULT 'Unassigned';
ALTER TABLE tasks ALTER COLUMN priority DROP NOT NULL;
ALTER TABLE tasks ALTER COLUMN priority SET DEFAULT 'medium';
ALTER TABLE tasks ALTER COLUMN status DROP NOT NULL;
ALTER TABLE tasks ALTER COLUMN status SET DEFAULT 'todo';
ALTER TABLE tasks ALTER COLUMN "dueDate" DROP NOT NULL;
ALTER TABLE tasks ALTER COLUMN "dueDate" SET DEFAULT CURRENT_DATE;
