import { AutomationAction } from './engine';

export const createSystemNotification = (message: string, type: 'info' | 'warning' | 'urgent' = 'info'): AutomationAction => {
  return async (supabase) => {
    // Requires an 'activities' or 'notifications' table. We use activities.
    const id = typeof crypto !== 'undefined' && typeof (crypto as any).randomUUID === 'function' 
      ? (crypto as any).randomUUID() 
      : `${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 10)}`;

    await supabase.from('activities').insert([{
      id,
      type: type === 'urgent' ? 'alert' : 'system',
      message,
      actor: 'System Automation',
      timestamp: new Date().toISOString()
    }]);
  };
};

export const generateDailyDashboardSummary: AutomationAction = async (supabase) => {
  // In a real implementation, this might call the AI endpoint to generate a summary
  // For now, we simulate the action by creating an activity record.
  
  const id = typeof crypto !== 'undefined' && typeof (crypto as any).randomUUID === 'function' 
      ? (crypto as any).randomUUID() 
      : `${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 10)}`;

  await supabase.from('activities').insert([{
    id,
    type: 'report',
    message: 'Daily dashboard summary generated by automation engine.',
    actor: 'System Automation',
    timestamp: new Date().toISOString()
  }]);
};
